/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountStatus } from './accountStatus';
import { KycResult } from './kycResult';

export class Account {
    'id'?: string;
    'accountNumber'?: string;
    'status'?: AccountStatus;
    /**
    * Always \"USD\"
    */
    'currency'?: string;
    'createdAt'?: Date;
    'lastEquity'?: string;
    'kycResults'?: KycResult;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "accountNumber",
            "baseName": "account_number",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AccountStatus"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "lastEquity",
            "baseName": "last_equity",
            "type": "string"
        },
        {
            "name": "kycResults",
            "baseName": "kyc_results",
            "type": "KycResult"
        }    ];

    static getAttributeTypeMap() {
        return Account.attributeTypeMap;
    }
}

