/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Contact } from './contact';
import { Disclosures } from './disclosures';
import { Identity } from './identity';
import { TrustedContact } from './trustedContact';

export class AccountUpdate {
    'contact'?: Contact;
    'identity'?: Identity;
    'disclosures'?: Disclosures;
    'trustedContact'?: TrustedContact;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contact",
            "baseName": "contact",
            "type": "Contact"
        },
        {
            "name": "identity",
            "baseName": "identity",
            "type": "Identity"
        },
        {
            "name": "disclosures",
            "baseName": "disclosures",
            "type": "Disclosures"
        },
        {
            "name": "trustedContact",
            "baseName": "trustedContact",
            "type": "TrustedContact"
        }    ];

    static getAttributeTypeMap() {
        return AccountUpdate.attributeTypeMap;
    }
}

