/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ACHRelationshipData } from './aCHRelationshipData';
import { ACHRelationshipResourceAllOf } from './aCHRelationshipResourceAllOf';
import { IdentifiedResource } from './identifiedResource';

export class ACHRelationshipResource {
    'id': string;
    'created_at': Date;
    'updated_at': Date;
    'account_owner_name': string;
    'bank_account_type': ACHRelationshipResource.BankAccountTypeEnum;
    'bank_account_number': string;
    'bank_routing_number': string;
    'nickname'?: string;
    'account_id': string;
    'status': ACHRelationshipResource.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "account_owner_name",
            "baseName": "account_owner_name",
            "type": "string"
        },
        {
            "name": "bank_account_type",
            "baseName": "bank_account_type",
            "type": "ACHRelationshipResource.BankAccountTypeEnum"
        },
        {
            "name": "bank_account_number",
            "baseName": "bank_account_number",
            "type": "string"
        },
        {
            "name": "bank_routing_number",
            "baseName": "bank_routing_number",
            "type": "string"
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string"
        },
        {
            "name": "account_id",
            "baseName": "account_id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ACHRelationshipResource.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return ACHRelationshipResource.attributeTypeMap;
    }
}

export namespace ACHRelationshipResource {
    export enum BankAccountTypeEnum {
        Checking = <any> 'CHECKING',
        Savings = <any> 'SAVINGS'
    }
    export enum StatusEnum {
        Queued = <any> 'QUEUED',
        Approved = <any> 'APPROVED',
        Pending = <any> 'PENDING',
        CancelRequested = <any> 'CANCEL_REQUESTED'
    }
}
