/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ACHRelationshipData {
    'account_owner_name': string;
    'bank_account_type': ACHRelationshipData.BankAccountTypeEnum;
    'bank_account_number': string;
    'bank_routing_number': string;
    'nickname'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "account_owner_name",
            "baseName": "account_owner_name",
            "type": "string"
        },
        {
            "name": "bank_account_type",
            "baseName": "bank_account_type",
            "type": "ACHRelationshipData.BankAccountTypeEnum"
        },
        {
            "name": "bank_account_number",
            "baseName": "bank_account_number",
            "type": "string"
        },
        {
            "name": "bank_routing_number",
            "baseName": "bank_routing_number",
            "type": "string"
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ACHRelationshipData.attributeTypeMap;
    }
}

export namespace ACHRelationshipData {
    export enum BankAccountTypeEnum {
        Checking = <any> 'CHECKING',
        Savings = <any> 'SAVINGS'
    }
}
