/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ACHRelationshipResourceAllOf {
    'account_id': string;
    'status': ACHRelationshipResourceAllOf.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "account_id",
            "baseName": "account_id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ACHRelationshipResourceAllOf.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return ACHRelationshipResourceAllOf.attributeTypeMap;
    }
}

export namespace ACHRelationshipResourceAllOf {
    export enum StatusEnum {
        Queued = <any> 'QUEUED',
        Approved = <any> 'APPROVED',
        Pending = <any> 'PENDING',
        CancelRequested = <any> 'CANCEL_REQUESTED'
    }
}
