/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActivityType } from './activityType';

/**
* Base for activity types
*/
export class Activity {
    'id'?: string;
    'account_id'?: string;
    'activity_type'?: ActivityType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "account_id",
            "baseName": "account_id",
            "type": "string"
        },
        {
            "name": "activity_type",
            "baseName": "activity_type",
            "type": "ActivityType"
        }    ];

    static getAttributeTypeMap() {
        return Activity.attributeTypeMap;
    }
}

