/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum ActivityType {
    Fill = <any> 'FILL',
    Acatc = <any> 'ACATC',
    Acats = <any> 'ACATS',
    Csd = <any> 'CSD',
    Csr = <any> 'CSR',
    Csw = <any> 'CSW',
    Div = <any> 'DIV',
    Divcgl = <any> 'DIVCGL',
    Divcgs = <any> 'DIVCGS',
    Divnra = <any> 'DIVNRA',
    Divroc = <any> 'DIVROC',
    Divtxex = <any> 'DIVTXEX',
    Int = <any> 'INT',
    Jnlc = <any> 'JNLC',
    Jnls = <any> 'JNLS',
    Ma = <any> 'MA',
    Nc = <any> 'NC',
    Ptc = <any> 'PTC',
    Reorg = <any> 'REORG',
    Sso = <any> 'SSO',
    Ssp = <any> 'SSP'
}
