/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DocumentType } from './documentType';

/**
* If an account has documents on the application submission, it has the ApplicationDocument model in exchange with DocumentUpload. 
*/
export class ApplicationDocument {
    'id': string;
    'document_type': DocumentType;
    'document_sub_type'?: string;
    'mime_type': string;
    'created_at': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "document_type",
            "baseName": "document_type",
            "type": "DocumentType"
        },
        {
            "name": "document_sub_type",
            "baseName": "document_sub_type",
            "type": "string"
        },
        {
            "name": "mime_type",
            "baseName": "mime_type",
            "type": "string"
        },
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return ApplicationDocument.attributeTypeMap;
    }
}

