/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BankData } from './bankData';
import { BankResourceAllOf } from './bankResourceAllOf';
import { IdentifiedResource } from './identifiedResource';

export class BankResource {
    'id': string;
    'created_at': Date;
    'updated_at': Date;
    'name': string;
    'bank_code': string;
    'bank_code_type': BankResource.BankCodeTypeEnum;
    'country'?: string;
    'state_province'?: string;
    'postal_code'?: string;
    'city'?: string;
    'street_address'?: string;
    'account_number': string;
    'account_id': string;
    'status': BankResource.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "bank_code",
            "baseName": "bank_code",
            "type": "string"
        },
        {
            "name": "bank_code_type",
            "baseName": "bank_code_type",
            "type": "BankResource.BankCodeTypeEnum"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "state_province",
            "baseName": "state_province",
            "type": "string"
        },
        {
            "name": "postal_code",
            "baseName": "postal_code",
            "type": "string"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "street_address",
            "baseName": "street_address",
            "type": "string"
        },
        {
            "name": "account_number",
            "baseName": "account_number",
            "type": "string"
        },
        {
            "name": "account_id",
            "baseName": "account_id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "BankResource.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return BankResource.attributeTypeMap;
    }
}

export namespace BankResource {
    export enum BankCodeTypeEnum {
        Aba = <any> 'ABA',
        Bic = <any> 'BIC'
    }
    export enum StatusEnum {
        Queued = <any> 'QUEUED',
        CancelRequested = <any> 'CANCEL_REQUESTED',
        SentToClearing = <any> 'SENT_TO_CLEARING',
        Approved = <any> 'APPROVED',
        Canceled = <any> 'CANCELED'
    }
}
