/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BatchJournalRequestEntries } from './batchJournalRequestEntries';

export class BatchJournalRequest {
    'entry_type': BatchJournalRequest.EntryTypeEnum;
    'from_account': string;
    'description'?: string;
    'entries'?: Array<BatchJournalRequestEntries>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entry_type",
            "baseName": "entry_type",
            "type": "BatchJournalRequest.EntryTypeEnum"
        },
        {
            "name": "from_account",
            "baseName": "from_account",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "entries",
            "baseName": "entries",
            "type": "Array<BatchJournalRequestEntries>"
        }    ];

    static getAttributeTypeMap() {
        return BatchJournalRequest.attributeTypeMap;
    }
}

export namespace BatchJournalRequest {
    export enum EntryTypeEnum {
        Jnlc = <any> 'JNLC'
    }
}
