/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Contact is the model for the account owner contact information. 
*/
export class Contact {
    'email_address'?: string;
    /**
    * with country code, no hyphen or space
    */
    'phone_number'?: string;
    'street_address'?: Array<string>;
    'city'?: string;
    'state'?: string;
    'postal_code'?: string;
    'country'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email_address",
            "baseName": "email_address",
            "type": "string"
        },
        {
            "name": "phone_number",
            "baseName": "phone_number",
            "type": "string"
        },
        {
            "name": "street_address",
            "baseName": "street_address",
            "type": "Array<string>"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "postal_code",
            "baseName": "postal_code",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Contact.attributeTypeMap;
    }
}

