/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Disclosures fields denote if the account owner falls under each category defined by FINRA rule. The client has to ask questions for the end user and the values should reflect their answers.  If one of the answers is true (yes), the account goes into ACTION_REQUIRED status. 
*/
export class Disclosures {
    'employment_status'?: Disclosures.EmploymentStatusEnum;
    'employer_name'?: string;
    'employer_address'?: string;
    'employment_position'?: string;
    'is_control_person': boolean;
    'is_affiliated_exchange_or_finra': boolean;
    'is_politically_exposed': boolean;
    'immediate_family_exposed': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "employment_status",
            "baseName": "employment_status",
            "type": "Disclosures.EmploymentStatusEnum"
        },
        {
            "name": "employer_name",
            "baseName": "employer_name",
            "type": "string"
        },
        {
            "name": "employer_address",
            "baseName": "employer_address",
            "type": "string"
        },
        {
            "name": "employment_position",
            "baseName": "employment_position",
            "type": "string"
        },
        {
            "name": "is_control_person",
            "baseName": "is_control_person",
            "type": "boolean"
        },
        {
            "name": "is_affiliated_exchange_or_finra",
            "baseName": "is_affiliated_exchange_or_finra",
            "type": "boolean"
        },
        {
            "name": "is_politically_exposed",
            "baseName": "is_politically_exposed",
            "type": "boolean"
        },
        {
            "name": "immediate_family_exposed",
            "baseName": "immediate_family_exposed",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Disclosures.attributeTypeMap;
    }
}

export namespace Disclosures {
    export enum EmploymentStatusEnum {
        Unemployed = <any> 'unemployed',
        Employed = <any> 'employed',
        Student = <any> 'student',
        Retired = <any> 'retired'
    }
}
