/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineResponse2005 {
    'account_id'?: string;
    'account_number'?: string;
    'status_from'?: string;
    'status_to'?: string;
    'reason'?: string;
    'at'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "account_id",
            "baseName": "account_id",
            "type": "string"
        },
        {
            "name": "account_number",
            "baseName": "account_number",
            "type": "string"
        },
        {
            "name": "status_from",
            "baseName": "status_from",
            "type": "string"
        },
        {
            "name": "status_to",
            "baseName": "status_to",
            "type": "string"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string"
        },
        {
            "name": "at",
            "baseName": "at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2005.attributeTypeMap;
    }
}

