/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineResponse20010 {
    'id'?: string;
    'account_id'?: string;
    'activity_type'?: InlineResponse20010.ActivityTypeEnum;
    'date'?: string;
    'net_amount'?: string;
    'description'?: string;
    'status'?: InlineResponse20010.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "account_id",
            "baseName": "account_id",
            "type": "string"
        },
        {
            "name": "activity_type",
            "baseName": "activity_type",
            "type": "InlineResponse20010.ActivityTypeEnum"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "net_amount",
            "baseName": "net_amount",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "InlineResponse20010.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20010.attributeTypeMap;
    }
}

export namespace InlineResponse20010 {
    export enum ActivityTypeEnum {
        Fill = <any> 'FILL',
        Acatc = <any> 'ACATC',
        Acats = <any> 'ACATS',
        Csd = <any> 'CSD',
        Csr = <any> 'CSR',
        Csw = <any> 'CSW',
        Div = <any> 'DIV',
        Divcgl = <any> 'DIVCGL',
        Divcgs = <any> 'DIVCGS',
        Divnra = <any> 'DIVNRA',
        Divroc = <any> 'DIVROC',
        Divtxex = <any> 'DIVTXEX',
        Int = <any> 'INT',
        Jnlc = <any> 'JNLC',
        Jnls = <any> 'JNLS',
        Ma = <any> 'MA',
        Nc = <any> 'NC',
        Ptc = <any> 'PTC',
        Reorg = <any> 'REORG',
        Sso = <any> 'SSO',
        Ssp = <any> 'SSP'
    }
    export enum StatusEnum {
        Executed = <any> 'executed',
        Canceled = <any> 'canceled'
    }
}
