/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountStatus } from './accountStatus';

export class InlineResponse200 {
    'id'?: string;
    'account_number'?: string;
    'status'?: AccountStatus;
    'currency'?: string;
    'buying_power'?: string;
    'regt_buying_power'?: string;
    'daytrading_buying_power'?: string;
    'cash'?: string;
    'cash_withdrawable'?: string;
    'cash_transferable'?: string;
    'pending_transfer_out'?: string;
    'portfolio_value'?: string;
    'pattern_day_trader'?: boolean;
    'trading_blocked'?: boolean;
    'transfers_blocked'?: boolean;
    'account_blocked'?: boolean;
    'created_at'?: string;
    'trade_suspended_by_user'?: boolean;
    'multiplier'?: string;
    'shorting_enabled'?: boolean;
    'equity'?: string;
    'last_equity'?: string;
    'long_market_value'?: string;
    'short_market_value'?: string;
    'initial_margin'?: string;
    'maintenance_margin'?: string;
    'last_maintenance_margin'?: string;
    'sma'?: string;
    'daytrade_count'?: number;
    'previous_close'?: string;
    'last_long_market_value'?: string;
    'last_short_market_value'?: string;
    'last_cash'?: string;
    'last_initial_margin'?: string;
    'last_regt_buying_power'?: string;
    'last_daytrading_buying_power'?: string;
    'last_buying_power'?: string;
    'last_daytrade_count'?: number;
    'clearing_broker'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "account_number",
            "baseName": "account_number",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AccountStatus"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "buying_power",
            "baseName": "buying_power",
            "type": "string"
        },
        {
            "name": "regt_buying_power",
            "baseName": "regt_buying_power",
            "type": "string"
        },
        {
            "name": "daytrading_buying_power",
            "baseName": "daytrading_buying_power",
            "type": "string"
        },
        {
            "name": "cash",
            "baseName": "cash",
            "type": "string"
        },
        {
            "name": "cash_withdrawable",
            "baseName": "cash_withdrawable",
            "type": "string"
        },
        {
            "name": "cash_transferable",
            "baseName": "cash_transferable",
            "type": "string"
        },
        {
            "name": "pending_transfer_out",
            "baseName": "pending_transfer_out",
            "type": "string"
        },
        {
            "name": "portfolio_value",
            "baseName": "portfolio_value",
            "type": "string"
        },
        {
            "name": "pattern_day_trader",
            "baseName": "pattern_day_trader",
            "type": "boolean"
        },
        {
            "name": "trading_blocked",
            "baseName": "trading_blocked",
            "type": "boolean"
        },
        {
            "name": "transfers_blocked",
            "baseName": "transfers_blocked",
            "type": "boolean"
        },
        {
            "name": "account_blocked",
            "baseName": "account_blocked",
            "type": "boolean"
        },
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "trade_suspended_by_user",
            "baseName": "trade_suspended_by_user",
            "type": "boolean"
        },
        {
            "name": "multiplier",
            "baseName": "multiplier",
            "type": "string"
        },
        {
            "name": "shorting_enabled",
            "baseName": "shorting_enabled",
            "type": "boolean"
        },
        {
            "name": "equity",
            "baseName": "equity",
            "type": "string"
        },
        {
            "name": "last_equity",
            "baseName": "last_equity",
            "type": "string"
        },
        {
            "name": "long_market_value",
            "baseName": "long_market_value",
            "type": "string"
        },
        {
            "name": "short_market_value",
            "baseName": "short_market_value",
            "type": "string"
        },
        {
            "name": "initial_margin",
            "baseName": "initial_margin",
            "type": "string"
        },
        {
            "name": "maintenance_margin",
            "baseName": "maintenance_margin",
            "type": "string"
        },
        {
            "name": "last_maintenance_margin",
            "baseName": "last_maintenance_margin",
            "type": "string"
        },
        {
            "name": "sma",
            "baseName": "sma",
            "type": "string"
        },
        {
            "name": "daytrade_count",
            "baseName": "daytrade_count",
            "type": "number"
        },
        {
            "name": "previous_close",
            "baseName": "previous_close",
            "type": "string"
        },
        {
            "name": "last_long_market_value",
            "baseName": "last_long_market_value",
            "type": "string"
        },
        {
            "name": "last_short_market_value",
            "baseName": "last_short_market_value",
            "type": "string"
        },
        {
            "name": "last_cash",
            "baseName": "last_cash",
            "type": "string"
        },
        {
            "name": "last_initial_margin",
            "baseName": "last_initial_margin",
            "type": "string"
        },
        {
            "name": "last_regt_buying_power",
            "baseName": "last_regt_buying_power",
            "type": "string"
        },
        {
            "name": "last_daytrading_buying_power",
            "baseName": "last_daytrading_buying_power",
            "type": "string"
        },
        {
            "name": "last_buying_power",
            "baseName": "last_buying_power",
            "type": "string"
        },
        {
            "name": "last_daytrade_count",
            "baseName": "last_daytrade_count",
            "type": "number"
        },
        {
            "name": "clearing_broker",
            "baseName": "clearing_broker",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse200.attributeTypeMap;
    }
}

