/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineResponse2006 {
    'event_id'?: number;
    'at'?: Date;
    'journal_id'?: string;
    'status_from'?: string;
    'status_to'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "event_id",
            "baseName": "event_id",
            "type": "number"
        },
        {
            "name": "at",
            "baseName": "at",
            "type": "Date"
        },
        {
            "name": "journal_id",
            "baseName": "journal_id",
            "type": "string"
        },
        {
            "name": "status_from",
            "baseName": "status_from",
            "type": "string"
        },
        {
            "name": "status_to",
            "baseName": "status_to",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2006.attributeTypeMap;
    }
}

