/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineResponse2007 {
    'clientId'?: string;
    'name'?: string;
    'description'?: string;
    'url'?: string;
    /**
    * URL of Terms of Use
    */
    'termsOfUse'?: string;
    /**
    * URL of Privacy Policy
    */
    'privacyPolicy'?: string;
    'status'?: InlineResponse2007.StatusEnum;
    'redirectUri'?: Array<string>;
    'liveTradingApproved'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clientId",
            "baseName": "client_id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "termsOfUse",
            "baseName": "terms_of_use",
            "type": "string"
        },
        {
            "name": "privacyPolicy",
            "baseName": "privacy_policy",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "InlineResponse2007.StatusEnum"
        },
        {
            "name": "redirectUri",
            "baseName": "redirect_uri",
            "type": "Array<string>"
        },
        {
            "name": "liveTradingApproved",
            "baseName": "live_trading_approved",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2007.attributeTypeMap;
    }
}

export namespace InlineResponse2007 {
    export enum StatusEnum {
        Active = <any> 'ACTIVE',
        Disabled = <any> 'DISABLED'
    }
}
