/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineResponse2004 {
    'documentId'?: string;
    /**
    * such as \"account_statement\" and \"trade_confirmation\"
    */
    'documentType'?: string;
    'documentDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "documentId",
            "baseName": "document_id",
            "type": "string"
        },
        {
            "name": "documentType",
            "baseName": "document_type",
            "type": "string"
        },
        {
            "name": "documentDate",
            "baseName": "document_date",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2004.attributeTypeMap;
    }
}

