/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineObject {
    'status'?: InlineObject.StatusEnum;
    'limit'?: number;
    'after'?: Date;
    'until'?: Date;
    'direction'?: InlineObject.DirectionEnum;
    'nested'?: boolean;
    'symbols'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "InlineObject.StatusEnum"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number"
        },
        {
            "name": "after",
            "baseName": "after",
            "type": "Date"
        },
        {
            "name": "until",
            "baseName": "until",
            "type": "Date"
        },
        {
            "name": "direction",
            "baseName": "direction",
            "type": "InlineObject.DirectionEnum"
        },
        {
            "name": "nested",
            "baseName": "nested",
            "type": "boolean"
        },
        {
            "name": "symbols",
            "baseName": "symbols",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineObject.attributeTypeMap;
    }
}

export namespace InlineObject {
    export enum StatusEnum {
        Open = <any> 'open',
        Closed = <any> 'closed',
        All = <any> 'all'
    }
    export enum DirectionEnum {
        Asc = <any> 'asc',
        Desc = <any> 'desc'
    }
}
