/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class JournalJNLC {
    /**
    * journal ID
    */
    'id': string;
    /**
    * JNLC (constant)
    */
    'entry_type': string;
    /**
    * account ID the amount goes from
    */
    'from_account': string;
    'to_account': string;
    /**
    * ID the amount goes to
    */
    'description'?: string;
    'settle_date': string | null;
    'status'?: JournalJNLC.StatusEnum;
    'net_amount': string;
    /**
    * max 255 characters
    */
    'transmitter_name'?: string;
    /**
    * max 255 characters
    */
    'transmitter_account_number'?: string;
    /**
    * max 255 characters
    */
    'transmitter_address'?: string;
    /**
    * max 255 characters
    */
    'transmitter_financial_institution'?: string;
    'transmitter_timestamp'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "entry_type",
            "baseName": "entry_type",
            "type": "string"
        },
        {
            "name": "from_account",
            "baseName": "from_account",
            "type": "string"
        },
        {
            "name": "to_account",
            "baseName": "to_account",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "settle_date",
            "baseName": "settle_date",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "JournalJNLC.StatusEnum"
        },
        {
            "name": "net_amount",
            "baseName": "net_amount",
            "type": "string"
        },
        {
            "name": "transmitter_name",
            "baseName": "transmitter_name",
            "type": "string"
        },
        {
            "name": "transmitter_account_number",
            "baseName": "transmitter_account_number",
            "type": "string"
        },
        {
            "name": "transmitter_address",
            "baseName": "transmitter_address",
            "type": "string"
        },
        {
            "name": "transmitter_financial_institution",
            "baseName": "transmitter_financial_institution",
            "type": "string"
        },
        {
            "name": "transmitter_timestamp",
            "baseName": "transmitter_timestamp",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return JournalJNLC.attributeTypeMap;
    }
}

export namespace JournalJNLC {
    export enum StatusEnum {
        Pending = <any> 'pending',
        Canceled = <any> 'canceled',
        Executed = <any> 'executed',
        Queued = <any> 'queued',
        Rejected = <any> 'rejected'
    }
}
