/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class JournalJNLS {
    /**
    * journal ID
    */
    'id': string;
    /**
    * JNLS (constant)
    */
    'entry_type': string;
    /**
    * account ID the shares go from
    */
    'from_account': string;
    /**
    * account ID the shares go to
    */
    'to_account': string;
    'settle_date': string;
    'status'?: JournalJNLS.StatusEnum;
    'symbol': string;
    'qty': string;
    'price': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "entry_type",
            "baseName": "entry_type",
            "type": "string"
        },
        {
            "name": "from_account",
            "baseName": "from_account",
            "type": "string"
        },
        {
            "name": "to_account",
            "baseName": "to_account",
            "type": "string"
        },
        {
            "name": "settle_date",
            "baseName": "settle_date",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "JournalJNLS.StatusEnum"
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string"
        },
        {
            "name": "qty",
            "baseName": "qty",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return JournalJNLS.attributeTypeMap;
    }
}

export namespace JournalJNLS {
    export enum StatusEnum {
        Pending = <any> 'pending',
        Canceled = <any> 'canceled',
        Executed = <any> 'executed'
    }
}
