/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Hold information about the result of KYC.
*/
export class KycResult {
    'reject'?: object;
    'accept'?: object;
    'indeterminate'?: object;
    'addidional_information'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reject",
            "baseName": "reject",
            "type": "object"
        },
        {
            "name": "accept",
            "baseName": "accept",
            "type": "object"
        },
        {
            "name": "indeterminate",
            "baseName": "indeterminate",
            "type": "object"
        },
        {
            "name": "addidional_information",
            "baseName": "addidional_information",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return KycResult.attributeTypeMap;
    }
}

