/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PatchOrder {
    'qty'?: string;
    'time_in_force'?: PatchOrder.TimeInForceEnum;
    'limit_price'?: string;
    'stop_price'?: string;
    'trail'?: string;
    'client_order_id'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "qty",
            "baseName": "qty",
            "type": "string"
        },
        {
            "name": "time_in_force",
            "baseName": "time_in_force",
            "type": "PatchOrder.TimeInForceEnum"
        },
        {
            "name": "limit_price",
            "baseName": "limit_price",
            "type": "string"
        },
        {
            "name": "stop_price",
            "baseName": "stop_price",
            "type": "string"
        },
        {
            "name": "trail",
            "baseName": "trail",
            "type": "string"
        },
        {
            "name": "client_order_id",
            "baseName": "client_order_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PatchOrder.attributeTypeMap;
    }
}

export namespace PatchOrder {
    export enum TimeInForceEnum {
        Day = <any> 'day',
        Gtc = <any> 'gtc',
        Opg = <any> 'opg',
        Cls = <any> 'cls',
        Ioc = <any> 'ioc',
        Fok = <any> 'fok'
    }
}
