/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Portfolio history
*/
export class PortfolioHistory {
    'timestamp'?: Array<number>;
    'equity'?: Array<number>;
    'profit_loss'?: Array<number>;
    'profit_loss_pct'?: Array<number>;
    'base_value'?: number;
    'timeframe'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Array<number>"
        },
        {
            "name": "equity",
            "baseName": "equity",
            "type": "Array<number>"
        },
        {
            "name": "profit_loss",
            "baseName": "profit_loss",
            "type": "Array<number>"
        },
        {
            "name": "profit_loss_pct",
            "baseName": "profit_loss_pct",
            "type": "Array<number>"
        },
        {
            "name": "base_value",
            "baseName": "base_value",
            "type": "number"
        },
        {
            "name": "timeframe",
            "baseName": "timeframe",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PortfolioHistory.attributeTypeMap;
    }
}

