/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Position {
    'asset_id'?: string;
    'symbol'?: string;
    'exchange'?: string;
    'asset_class'?: string;
    'avg_entry_price'?: string;
    'qty'?: string;
    'side'?: string;
    'market_value'?: string;
    'cost_basis'?: string;
    'unrealized_pl'?: string;
    'unrealized_plpc'?: string;
    'unrealized_intraday_pl'?: string;
    'unrealized_intraday_plpc'?: string;
    'current_price'?: string;
    'lastday_price'?: string;
    'change_today'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "asset_id",
            "baseName": "asset_id",
            "type": "string"
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string"
        },
        {
            "name": "exchange",
            "baseName": "exchange",
            "type": "string"
        },
        {
            "name": "asset_class",
            "baseName": "asset_class",
            "type": "string"
        },
        {
            "name": "avg_entry_price",
            "baseName": "avg_entry_price",
            "type": "string"
        },
        {
            "name": "qty",
            "baseName": "qty",
            "type": "string"
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "string"
        },
        {
            "name": "market_value",
            "baseName": "market_value",
            "type": "string"
        },
        {
            "name": "cost_basis",
            "baseName": "cost_basis",
            "type": "string"
        },
        {
            "name": "unrealized_pl",
            "baseName": "unrealized_pl",
            "type": "string"
        },
        {
            "name": "unrealized_plpc",
            "baseName": "unrealized_plpc",
            "type": "string"
        },
        {
            "name": "unrealized_intraday_pl",
            "baseName": "unrealized_intraday_pl",
            "type": "string"
        },
        {
            "name": "unrealized_intraday_plpc",
            "baseName": "unrealized_intraday_plpc",
            "type": "string"
        },
        {
            "name": "current_price",
            "baseName": "current_price",
            "type": "string"
        },
        {
            "name": "lastday_price",
            "baseName": "lastday_price",
            "type": "string"
        },
        {
            "name": "change_today",
            "baseName": "change_today",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Position.attributeTypeMap;
    }
}

