/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TransferDataAllOf } from './transferDataAllOf';

export class TransferData {
    'transfer_type': TransferData.TransferTypeEnum;
    'timing'?: TransferData.TimingEnum;
    'amount': string;
    'direction': TransferData.DirectionEnum;
    'relationship_id': string;
    'additional_information'?: string;
    'bank_id': string;

    static discriminator: string | undefined = "transfer_type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "transfer_type",
            "baseName": "transfer_type",
            "type": "TransferData.TransferTypeEnum"
        },
        {
            "name": "timing",
            "baseName": "timing",
            "type": "TransferData.TimingEnum"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "direction",
            "baseName": "direction",
            "type": "TransferData.DirectionEnum"
        },
        {
            "name": "relationship_id",
            "baseName": "relationship_id",
            "type": "string"
        },
        {
            "name": "additional_information",
            "baseName": "additional_information",
            "type": "string"
        },
        {
            "name": "bank_id",
            "baseName": "bank_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TransferData.attributeTypeMap;
    }
}

export namespace TransferData {
    export enum TransferTypeEnum {
        Ach = <any> 'ach',
        Wire = <any> 'wire'
    }
    export enum TimingEnum {
        Immediate = <any> 'immediate'
    }
    export enum DirectionEnum {
        Incoming = <any> 'INCOMING',
        Outgoing = <any> 'OUTGOING'
    }
}
