/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TransferDataAllOf {
    'transferType': TransferDataAllOf.TransferTypeEnum;
    'timing'?: TransferDataAllOf.TimingEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "transferType",
            "baseName": "transfer_type",
            "type": "TransferDataAllOf.TransferTypeEnum"
        },
        {
            "name": "timing",
            "baseName": "timing",
            "type": "TransferDataAllOf.TimingEnum"
        }    ];

    static getAttributeTypeMap() {
        return TransferDataAllOf.attributeTypeMap;
    }
}

export namespace TransferDataAllOf {
    export enum TransferTypeEnum {
        Ach = <any> 'ach',
        Wire = <any> 'wire'
    }
    export enum TimingEnum {
        Immediate = <any> 'immediate'
    }
}
