/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* This model input is optional. However, the client should make reasonable effort to obtain the trusted contact information. See more details in [FINRA Notice 17-11](https://www.finra.org/sites/default/files/Regulatory-Notice-17-11.pdf) 
*/
export class TrustedContact {
    'given_name': string;
    'family_name': string;
    /**
    * at least one of `email_address`, `phone_number` or `street_address` is required 
    */
    'email_address'?: string;
    /**
    * at least one of `email_address`, `phone_number` or `street_address` is required 
    */
    'phone_number'?: string;
    /**
    * at least one of `email_address`, `phone_number` or `street_address` is required 
    */
    'street_address'?: Array<string>;
    /**
    * required if `street_address` is set 
    */
    'city'?: string;
    /**
    * required if `street_address` is set 
    */
    'state'?: string;
    /**
    * required if `street_address` is set 
    */
    'postal_code'?: string;
    /**
    * [ISO 3166-1 alpha-3](https://www.iso.org/iso-3166-country-codes.html). required if `street_address` is set 
    */
    'country'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "given_name",
            "baseName": "given_name",
            "type": "string"
        },
        {
            "name": "family_name",
            "baseName": "family_name",
            "type": "string"
        },
        {
            "name": "email_address",
            "baseName": "email_address",
            "type": "string"
        },
        {
            "name": "phone_number",
            "baseName": "phone_number",
            "type": "string"
        },
        {
            "name": "street_address",
            "baseName": "street_address",
            "type": "Array<string>"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "postal_code",
            "baseName": "postal_code",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TrustedContact.attributeTypeMap;
    }
}

