/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UntypedTransferData } from './untypedTransferData';
import { UntypedWireTransferDataAllOf } from './untypedWireTransferDataAllOf';

export class UntypedWireTransferData {
    'amount': string;
    'direction': UntypedWireTransferData.DirectionEnum;
    'additionalInformation'?: string;
    'bankId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "direction",
            "baseName": "direction",
            "type": "UntypedWireTransferData.DirectionEnum"
        },
        {
            "name": "additionalInformation",
            "baseName": "additional_information",
            "type": "string"
        },
        {
            "name": "bankId",
            "baseName": "bank_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UntypedWireTransferData.attributeTypeMap;
    }
}

export namespace UntypedWireTransferData {
    export enum DirectionEnum {
        Incoming = <any> 'INCOMING',
        Outgoing = <any> 'OUTGOING'
    }
}
